"""Extract ENGINEERING-review additions from the reviewed markdown and emit a .docx.

Uses a diff against the original document so only genuinely added content is captured.
Each addition is grouped under the nearest preceding section heading for context, and
the added text is highlighted so it is easy to spot when pasting into the Word file.
"""

import difflib
import re
from pathlib import Path

from docx import Document
from docx.enum.text import WD_COLOR_INDEX
from docx.shared import Pt, RGBColor

DOC_DIR = Path("document")
ORIGINAL = DOC_DIR / "Microsoft Foundry adoption across my organization.md"
REVIEWED = DOC_DIR / "Microsoft Foundry adoption across my organization_reviewed.md"
OUTPUT = DOC_DIR / "Microsoft Foundry adoption - ENGINEERING additions.docx"

MARKER_RE = re.compile(r"<!--\s*Added based on .*?review\s*-->", re.IGNORECASE)
LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
BOLD_RE = re.compile(r"\*\*(.+?)\*\*")


def is_heading(line: str) -> bool:
    """A heading is a line that is entirely bold text, e.g. **Section Title**."""
    s = line.strip()
    return bool(s) and s.startswith("**") and s.endswith("**") and s.count("**") == 2


def clean_inline(text: str) -> str:
    """Strip markdown links to 'text (url)' and remove bold markers for plain runs."""
    text = MARKER_RE.sub("", text)
    text = LINK_RE.sub(lambda m: f"{m.group(1)} ({m.group(2)})", text)
    text = BOLD_RE.sub(lambda m: m.group(1), text)
    return text.strip()


def nearest_heading(rev_lines: list[str], idx: int) -> str:
    """Walk backwards from idx to find the nearest bold-only heading line."""
    for k in range(idx, -1, -1):
        if is_heading(rev_lines[k]):
            return rev_lines[k].strip().strip("*").strip()
    return "Document"


def main() -> None:
    orig = ORIGINAL.read_text(encoding="utf-8").splitlines()
    rev = REVIEWED.read_text(encoding="utf-8").splitlines()

    sm = difflib.SequenceMatcher(a=orig, b=rev, autojunk=False)

    # Collect additions grouped by their nearest preceding heading, preserving order.
    grouped: list[tuple[str, list[str]]] = []
    for tag, _i1, _i2, j1, j2 in sm.get_opcodes():
        if tag not in ("insert", "replace"):
            continue
        block = [rev[j] for j in range(j1, j2)]
        # Only keep lines that are genuinely new additions (markered or non-empty content
        # within an inserted region).
        content = [l for l in block if l.strip()]
        if not content:
            continue
        heading = nearest_heading(rev, j1 - 1 if j1 > 0 else 0)
        grouped.append((heading, content))

    # Merge consecutive blocks that share the same heading.
    merged: list[tuple[str, list[str]]] = []
    for heading, content in grouped:
        if merged and merged[-1][0] == heading:
            merged[-1][1].extend(content)
        else:
            merged.append((heading, list(content)))

    doc = Document()

    title = doc.add_heading("Engineering Review — Suggested Additions", level=0)
    intro = doc.add_paragraph()
    intro.add_run(
        "The passages below were generated by the engineering-perspective documentation "
        "review. Each block is grouped under the section heading where it belongs in "
        "“Microsoft Foundry adoption across my organization”. Highlighted text is the "
        "suggested new content to paste into the Word document."
    ).italic = True

    for heading, content in merged:
        doc.add_heading(heading, level=1)

        for raw in content:
            line = raw.rstrip()
            if not line.strip():
                continue

            # Checklist table rows: "|  | <text> |" -> bullet.
            table_row = re.match(r"^\|\s*\|\s*(.*?)\s*\|\s*$", line)
            if table_row:
                text = clean_inline(table_row.group(1))
                if not text:
                    continue
                p = doc.add_paragraph(style="List Bullet")
                run = p.add_run(text)
                run.font.highlight_color = WD_COLOR_INDEX.YELLOW
                continue

            # Numbered list item.
            num = re.match(r"^\s*(\d+)\.\s+(.*)$", line)
            if num:
                text = clean_inline(num.group(2))
                p = doc.add_paragraph(style="List Number")
                run = p.add_run(text)
                run.font.highlight_color = WD_COLOR_INDEX.YELLOW
                continue

            # Bulleted list item.
            bullet = re.match(r"^\s*[-*]\s+(.*)$", line)
            if bullet:
                text = clean_inline(bullet.group(1))
                p = doc.add_paragraph(style="List Bullet")
                run = p.add_run(text)
                run.font.highlight_color = WD_COLOR_INDEX.YELLOW
                continue

            # Sub-heading inside an addition (entirely bold).
            if is_heading(line):
                p = doc.add_paragraph()
                run = p.add_run(line.strip().strip("*").strip())
                run.bold = True
                run.font.highlight_color = WD_COLOR_INDEX.YELLOW
                continue

            # Regular paragraph (may contain inline bold).
            text = clean_inline(line)
            if not text:
                continue
            p = doc.add_paragraph()
            run = p.add_run(text)
            run.font.highlight_color = WD_COLOR_INDEX.YELLOW

    doc.save(OUTPUT)
    print(f"Saved: {OUTPUT}")
    print(f"Sections with additions: {len(merged)}")


if __name__ == "__main__":
    main()
