"""Foundry Hosted Agent entrypoint for the doc-reviewer orchestrator.

Self-contained deploy package: the `doc_reviewer` package is vendored alongside
this file so it is importable from the ZIP root. Generated by the deploy build;
edit the source under `src/doc_reviewer/host/` instead.
"""
from doc_reviewer.host.server import run

run()
